---
title: "Poročilo pri predmetu Analiza podatkov s programom R"
author: "Študent FMF"
output:
  pdf_document:
    latex_engine: xelatex
    includes:
      in_header: lib/styles.sty
---

```{r setup, echo=FALSE, results='hide', message=FALSE}
# Če želimo nastaviti pisave v PDF-ju, odkomentiramo
# in sledimo navodilom v programu.
#source("fontconfig.r", encoding = "UTF-8")

# Uvoz vseh potrebnih knjižnic
source("lib/libraries.r", encoding = "UTF-8")
```

# Izbira teme

Analiziral bom povprečno število dijakov/študentov
v posameznih stopnjah izobrazbe in 
razmerje učencev na učitelja v državah OECD.
Skušal bom odkriti kje so razmere za učenje 
znotraj razreda najslabše glede na te podatke. 

***

# Obdelava, uvoz in čiščenje podatkov

```
source("uvoz/uvoz.r", encoding = "UTF-8")
```
Podatke sem črpal predvsem iz uradne internetne strani 
statističnega ureda OECD, saj sem tam pridobil vse, 
kar sem potreboval. 
Iz tam sem prekopiral 2 tabeli, ki sem jih 
kasneje preuredil tako, 
kot bom to potreboval za naslednjo stopnjo projekta. 

```
kable(razmerje)
```

Tabela razmerje prikazuje koliko učencev uči povprečen učitelj v določeni državi. 
Za vsako državo OECD imamo 6 tipov podatkov. 
Najprej ločimo primarno stopnjo izobraževanja (kar je pri nas osnovna šola) 
in sekundarno stopnjo izobraževanja. 
Nato ločimo še učne inštitute na javne, zasebne in skupek obeh skupaj. 

```
kable(povprecje)
```

Tabela povprecje pa prikazuje povprečno število učencev v razredu v posameznih državah.
Tako kot v prejšnji tabeli sem tudi tukaj ločil podatke
na primarno in sekundrano stopnjo izobraževanja ter na javne, zasebne ali skupek obeh. 

```
ggplot(data=razmerje, aes(x=Drzava, y=`Primarna stopnja izobrazbe`)) + geom_point(colour="black", size=5)
```
Da si podatke lažje predstavljamo sem jih predstavil na večih grafih. Prvi prikazuje 
povprečno število dijakov na profesorja v primarni stopnji izobraževanja.

```
ggplot(data=razmerje, aes(x=Drzava, y=`Sekundarna stopnja izobrazbe`)) + geom_point(colour="blue", size=5, shape=21)
```
Tu sem prikazal iste podatke kot v prejšnji tabeli, le da sem tu gledal sekundarno stopnjo izobrazbe.

```
ggplot(data=povprecje, aes(x=Drzava, y=`Primarna stopnja izobrazbe`)) + geom_point(colour="blue", size=5)
```
Nato sem narisal še graf, ki prikazuje povprečno število dijakov v razredu primarne stopnje izobraževanja.

```
ggplot(data=povprecje, aes(x=Drzava, y=`Sekundarna stopnja izobrazbe`)) + geom_point(colour="green", size=5)
```
Nazadnje pa sem narisal še graf, ki prikazuje povprečno število dijakov v razredu sekundarne stopnje izobraževanja. 
